apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: one-gate-payment
  labels:
    app: one-gate-payment
    component: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: proxy
  selector:
    app: one-gate-payment
    component: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: one-gate-payment
  labels:
    app: one-gate-payment
    component: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      name: admin-api
    - port: 8002
      targetPort: 8002
      name: admin-gui
  selector:
    app: one-gate-payment
    component: gateway