apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
  namespace: one-gate-payment
  labels:
    app: one-gate-payment
    component: migration
spec:
  template:
    metadata:
      labels:
        app: one-gate-payment
        component: migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kong-migration
          image: kong/kong-gateway:3.8.1.2-20250724-rhel-fips
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: kong-database
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: username
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: password
            - name: KONG_PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: database
          command: ["kong", "migrations", "bootstrap"]