apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  namespace: one-gate-payment
  labels:
    app: one-gate-payment
    component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-gate-payment
      component: gateway
  template:
    metadata:
      labels:
        app: one-gate-payment
        component: gateway
    spec:
      containers:
        - name: kong
          image: kong/kong-gateway:3.8.1.2-20250724-rhel-fips
          env:
            # Database credentials from secrets
            - name: KONG_PG_USER
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: username
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: password
            - name: KONG_PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: database
            # Use configuration from ConfigMap
            - name: KONG_CONF
              value: /etc/kong/kong.conf
          ports:
            - containerPort: 8000
              name: proxy
            - containerPort: 8001
              name: admin-api
            - containerPort: 8002
              name: admin-gui
          livenessProbe:
            httpGet:
              path: /status
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong/kong.conf
              subPath: kong.conf
      volumes:
        - name: kong-config
          configMap:
            name: kong-config