apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: one-gate-payment
  labels:
    app: one-gate-payment
    component: gateway
data:
  kong.conf: |
    # Database configuration
    database = postgres
    pg_host = kong-database
    pg_port = 5432
    
    # Logging configuration
    proxy_access_log = /dev/stdout
    admin_access_log = /dev/stdout  
    proxy_error_log = /dev/stderr
    admin_error_log = /dev/stderr
    log_level = notice
    
    # Admin API
    admin_listen = 0.0.0.0:8001
    admin_gui_listen = 0.0.0.0:8002
    admin_gui_url = http://localhost:8002
    
    # Proxy configuration
    proxy_listen = 0.0.0.0:8000
    
    # Plugin configuration (essential plugins only)
    plugins = bundled,jwt,key-auth,rate-limiting,cors