apiVersion: v1
kind: Service
metadata:
  name: kong-database
  namespace: one-gate-payment
  labels:
    app: one-gate-payment
    component: database
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: one-gate-payment
    component: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kong-database
  namespace: one-gate-payment
  labels:
    app: one-gate-payment
    component: database
spec:
  serviceName: kong-database
  replicas: 1
  selector:
    matchLabels:
      app: one-gate-payment
      component: database
  template:
    metadata:
      labels:
        app: one-gate-payment
        component: database
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: kong-postgres-secret
                  key: database
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: kong-postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: kong-postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: kong-postgres-config
              mountPath: /docker-entrypoint-initdb.d/postgresql.conf
              subPath: postgresql.conf
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
                - -d
                - $(POSTGRES_DB)
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
                - -d
                - $(POSTGRES_DB)
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: kong-postgres-config
          configMap:
            name: kong-postgres-config
  volumeClaimTemplates:
    - metadata:
        name: kong-postgres-storage
        labels:
          app: one-gate-payment
          component: database
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ssd-csi
        resources:
          requests:
            storage: 20Gi