apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability-one-gate-payment
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: otel_collector
        honor_timestamps: true
        scrape_interval: 12s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - otel-collector:8888