apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus
  namespace: observability-one-gate-payment
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--enable-feature=exemplar-storage'
            - '--web.enable-remote-write-receiver'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
            - name: data-volume
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: data-volume
          emptyDir: {}

---
# Service for Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observability-one-gate-payment
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090

---
# Route for external access
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
  namespace: observability-one-gate-payment
spec:
  to:
    kind: Service
    name: prometheus