apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
  namespace: one-gate-payment
  labels:
    app: one-gate-payment-db
    component: migration
spec:
  # Job will be retried up to 3 times if it fails
  backoffLimit: 3

  # Job will be cleaned up after 24 hours of completion
  ttlSecondsAfterFinished: 86400

  template:
    metadata:
      labels:
        app: one-gate-payment-db
        component: migration
    spec:
      restartPolicy: Never

      # Init container to wait for PostgreSQL to be ready
      initContainers:
        - name: wait-for-postgres
          image: postgres:17-alpine
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h postgresql-service.one-gate-payment.svc.cluster.local -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB; do
                echo "PostgreSQL not ready yet, waiting 5 seconds..."
                sleep 5
              done
              echo "PostgreSQL is ready!"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_DB

      containers:
        - name: flyway-migration
          image: flyway/flyway:10-alpine

          # Flyway command arguments
          args:
            - -url=jdbc:postgresql://postgresql-service.one-gate-payment.svc.cluster.local:5432/one_gate_payment
            - -locations=filesystem:/flyway/sql
            - -validateMigrationNaming=true
            - -baselineOnMigrate=true
            - -connectRetries=10
            - -connectRetriesInterval=5
            - migrate

          # Environment variables
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://postgresql-service:5432/one_gate_payment"
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: FLYWAY_LOCATIONS
              value: "filesystem:/flyway/sql"
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: FLYWAY_VALIDATE_MIGRATION_NAMING
              value: "true"

          # Resource limits for flyway job
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "512Mi"

          # Volume mounts for flyway migrations
          volumeMounts:
            - name: flyway-migrations-volume
              mountPath: /flyway/sql
              readOnly: true

      # Volumes
      volumes:
        - name: flyway-migrations-volume
          configMap:
            name: flyway-migrations
