apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-migrations
  namespace: one-gate-payment
  labels:
    app: one-gate-payment-db
    component: flyway
data:
  V1__create_users_table.sql: |
    CREATE TABLE users
    (
        id         SERIAL PRIMARY KEY,
        username   VARCHAR(255) NOT NULL UNIQUE,
        email      VARCHAR(255) NOT NULL UNIQUE,
        phone      VARCHAR(20)  NOT NULL UNIQUE,
        password   VARCHAR(255) NOT NULL,
        created_at TIMESTAMP    NOT NULL DEFAULT now(),
        updated_at TIMESTAMP    NOT NULL DEFAULT now()
    );

    CREATE INDEX idx_users_email ON users (email);
    CREATE INDEX idx_users_username ON users (username);
    CREATE INDEX idx_users_created_at ON users (created_at);
    CREATE INDEX idx_users_phone ON users (phone);

  V2__create_authentications_table.sql: |
    CREATE TABLE authentications
    (
        token      VARCHAR(512) PRIMARY KEY,
        user_id    SERIAL NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        created_at TIMESTAMP   NOT NULL DEFAULT now()
    );

    CREATE INDEX idx_authentications_user_id ON authentications(user_id);
    CREATE INDEX idx_authentications_created_at ON authentications(created_at);

  V3__create_accounts_table.sql: |
    CREATE TYPE account_status_enum AS ENUM ('ACTIVE', 'SUSPENDED', 'CLOSED');

    CREATE TABLE accounts
    (
        id             VARCHAR(36) PRIMARY KEY      DEFAULT gen_random_uuid(),
        user_id        BIGINT              NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
        balance        DECIMAL(15, 2)      NOT NULL DEFAULT 0.00,
        currency       VARCHAR(3)          NOT NULL DEFAULT 'IDR',
        account_status account_status_enum NOT NULL DEFAULT 'ACTIVE',
        created_at     TIMESTAMP           NOT NULL DEFAULT now(),
        updated_at     TIMESTAMP           NOT NULL DEFAULT now()
    );

    CREATE INDEX idx_accounts_user_id ON accounts(user_id);
    CREATE INDEX idx_accounts_account_status ON accounts(account_status);
    CREATE INDEX idx_accounts_currency ON accounts(currency);
    CREATE INDEX idx_accounts_created_at ON accounts(created_at);
    CREATE INDEX idx_accounts_updated_at ON accounts(updated_at);

  V4__create_historical_transactions_table.sql: |
    CREATE TYPE transaction_type_enum AS ENUM ('TOPUP', 'PAYMENT', 'REFUND', 'TRANSFER');
    CREATE TYPE transaction_status_enum AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED');
    CREATE TYPE payment_method_enum AS ENUM ('GOPAY', 'SHOPEE_PAY');

    CREATE TABLE historical_transactions
    (
        id                     VARCHAR(36) PRIMARY KEY          DEFAULT gen_random_uuid(),
        user_id                BIGINT                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        account_id             VARCHAR(36)             NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
        transaction_id         VARCHAR(50)             NOT NULL UNIQUE,
        transaction_type       transaction_type_enum   NOT NULL,
        transaction_status     transaction_status_enum NOT NULL,
        amount                 DECIMAL(15, 2)          NOT NULL,
        balance_before         DECIMAL(15, 2)          NOT NULL,
        balance_after          DECIMAL(15, 2)          NOT NULL,
        currency               VARCHAR(3)              NOT NULL DEFAULT 'IDR',
        description            TEXT,
        external_reference     VARCHAR(255),
        payment_method         payment_method_enum,
        metadata               TEXT,
        is_accessible_external BOOLEAN                 NOT NULL DEFAULT true,
        created_at             TIMESTAMP               NOT NULL DEFAULT now(),
        updated_at             TIMESTAMP               NOT NULL DEFAULT now()
    );

    CREATE INDEX idx_historical_transactions_user_id ON historical_transactions(user_id);
    CREATE INDEX idx_historical_transactions_account_id ON historical_transactions(account_id);
    CREATE INDEX idx_historical_transactions_transaction_id ON historical_transactions(transaction_id);
    CREATE INDEX idx_historical_transactions_transaction_type ON historical_transactions(transaction_type);
    CREATE INDEX idx_historical_transactions_transaction_status ON historical_transactions(transaction_status);
    CREATE INDEX idx_historical_transactions_payment_method ON historical_transactions(payment_method);
    CREATE INDEX idx_historical_transactions_created_at ON historical_transactions(created_at);
    CREATE INDEX idx_historical_transactions_updated_at ON historical_transactions(updated_at);
    CREATE INDEX idx_historical_transactions_external_reference ON historical_transactions(external_reference);
    CREATE INDEX idx_historical_transactions_is_accessible_external ON historical_transactions(is_accessible_external);

    CREATE INDEX idx_historical_transactions_user_type_status ON historical_transactions(user_id, transaction_type, transaction_status, payment_method);
    CREATE INDEX idx_historical_transactions_user_created_at ON historical_transactions(user_id, created_at DESC);
    CREATE INDEX idx_historical_transactions_type_status_created ON historical_transactions(transaction_type, transaction_status, created_at DESC);
    CREATE INDEX idx_historical_transactions_status_created ON historical_transactions(transaction_status, created_at DESC);
    CREATE INDEX idx_historical_transactions_accessible_created ON historical_transactions(is_accessible_external, created_at DESC);

  V5__create_external_services_table.sql: |
    CREATE TABLE external_services
    (
        id            VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
        company       VARCHAR(255) NOT NULL UNIQUE,
        service_type  VARCHAR(50)  NOT NULL   DEFAULT 'HISTORICAL_TRANSACTION',
        contact_email VARCHAR(255) NOT NULL,
        description   TEXT,
        is_active     BOOLEAN      NOT NULL   DEFAULT true,
        created_at    TIMESTAMP    NOT NULL   DEFAULT now(),
        updated_at    TIMESTAMP    NOT NULL   DEFAULT now()
    );

    CREATE INDEX idx_external_services_company ON external_services(company);
    CREATE INDEX idx_external_services_service_type ON external_services(service_type);
    CREATE INDEX idx_external_services_is_active ON external_services(is_active);
    CREATE INDEX idx_external_services_created_at ON external_services(created_at);

  V6__create_api_keys_table.sql: |
    CREATE TYPE permissions_enum AS ENUM ('READ_TRANSACTIONS', 'READ_REPORTS',
        'READ_TRANSACTIONS,READ_REPORTS');
    CREATE TYPE rate_limit_unit_enum AS ENUM ('second', 'minute', 'hour', 'day');

    CREATE TABLE api_keys
    (
        id                  VARCHAR(36) PRIMARY KEY       DEFAULT gen_random_uuid(),
        external_service_id VARCHAR(36)          NOT NULL UNIQUE REFERENCES external_services (id) ON DELETE CASCADE,
        key_name            VARCHAR(255)         NOT NULL,
        permissions         permissions_enum     NOT NULL,
        rate_limit_count    INTEGER,
        rate_limit_unit     rate_limit_unit_enum NOT NULL DEFAULT 'minute',
        expires_at          TIMESTAMP,
        is_active           BOOLEAN              NOT NULL DEFAULT true,
        created_at          TIMESTAMP            NOT NULL DEFAULT now(),
        updated_at          TIMESTAMP            NOT NULL DEFAULT now()
    );

    CREATE INDEX idx_api_keys_external_service_id ON api_keys (external_service_id);
    CREATE INDEX idx_api_keys_is_active ON api_keys (is_active);
    CREATE INDEX idx_api_keys_expires_at ON api_keys (expires_at);
    CREATE INDEX idx_api_keys_permissions ON api_keys (permissions);
    CREATE INDEX idx_api_keys_created_at ON api_keys (created_at);
    CREATE INDEX idx_api_keys_rate_limit_count ON api_keys (rate_limit_count);
    CREATE INDEX idx_api_keys_rate_limit_unit ON api_keys (rate_limit_unit);
    CREATE INDEX idx_api_keys_rate_limit_composite ON api_keys (rate_limit_count, rate_limit_unit, is_active);

  V7__create_api_access_logs_table.sql: |
    CREATE TYPE http_method_enum AS ENUM ('GET', 'POST', 'PUT', 'DELETE', 'PATCH');

    CREATE TABLE api_access_logs
    (
        id                  VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
        external_service_id VARCHAR(36) NOT NULL REFERENCES external_services (id) ON DELETE CASCADE,
        api_key_id          VARCHAR(36) NOT NULL REFERENCES api_keys (id) ON DELETE CASCADE,
        endpoint            VARCHAR(255),
        http_method         http_method_enum,
        ip_address          TEXT,
        user_agent          TEXT,
        response_status     INTEGER,
        created_at          TIMESTAMP               DEFAULT now()
    );
    
    CREATE INDEX idx_api_access_logs_external_service_id ON api_access_logs (external_service_id);
    CREATE INDEX idx_api_access_logs_created_at ON api_access_logs (created_at DESC);
    CREATE INDEX idx_api_access_logs_ip_address ON api_access_logs (ip_address);
    CREATE INDEX idx_api_access_logs_http_method ON api_access_logs (http_method);
    CREATE INDEX idx_api_access_logs_user_agent ON api_access_logs (user_agent);
    CREATE INDEX idx_api_access_logs_endpoint ON api_access_logs (endpoint);
    CREATE INDEX idx_api_access_logs_response_status ON api_access_logs (response_status);

  V8__dummy_records.sql: |
    -- Insert dummy users
    INSERT INTO users (id, username, email, phone, password, created_at, updated_at)
    VALUES (1, 'john_doe', 'john.doe@example.com', '082181707745',
            '$argon2id$v=19$m=16384,t=2,p=1$PoQbisWKt769EMs6KE+D6Q$dlJIy5ThpYEQMXfeSheNvwy6hfL6cXXdoOJhPmJFAYo',
            '2024-01-15 10:30:00', '2024-01-15 10:30:00'),
           (2, 'jane_smith', 'jane.smith@example.com', '081293846571',
            '$argon2id$v=19$m=16384,t=2,p=1$PoQbisWKt769EMs6KE+D6Q$dlJIy5ThpYEQMXfeSheNvwy6hfL6cXXdoOJhPmJFAYo',
            '2024-01-16 14:20:00', '2024-01-16 14:20:00'),
           (3, 'ahmad_budi', 'ahmad.budi@gmail.com', '085773092184',
            '$argon2id$v=19$m=16384,t=2,p=1$PoQbisWKt769EMs6KE+D6Q$dlJIy5ThpYEQMXfeSheNvwy6hfL6cXXdoOJhPmJFAYo',
            '2024-01-17 09:15:00', '2024-01-17 09:15:00'),
           (4, 'siti_nurhaliza', 'siti.nurhaliza@yahoo.com', '087812349091',
            '$argon2id$v=19$m=16384,t=2,p=1$PoQbisWKt769EMs6KE+D6Q$dlJIy5ThpYEQMXfeSheNvwy6hfL6cXXdoOJhPmJFAYo',
            '2024-01-18 16:45:00', '2024-01-18 16:45:00'),
           (5, 'david_tan', 'david.tan@company.co.id', '082229901765',
            '$argon2id$v=19$m=16384,t=2,p=1$PoQbisWKt769EMs6KE+D6Q$dlJIy5ThpYEQMXfeSheNvwy6hfL6cXXdoOJhPmJFAYo',
            '2024-01-19 11:30:00', '2024-01-19 11:30:00'),
           (6, 'rina_kusuma', 'rina.kusuma@outlook.com', '081317758842',
            '$argon2id$v=19$m=16384,t=2,p=1$PoQbisWKt769EMs6KE+D6Q$dlJIy5ThpYEQMXfeSheNvwy6hfL6cXXdoOJhPmJFAYo',
            '2024-01-20 08:15:00', '2024-01-20 08:15:00'),
           (7, 'bayu_setiawan', 'bayu.setiawan@gmail.com', '085266104738',
            '$argon2id$v=19$m=16384,t=2,p=1$PoQbisWKt769EMs6KE+D6Q$dlJIy5ThpYEQMXfeSheNvwy6hfL6cXXdoOJhPmJFAYo',
            '2024-01-20 10:45:00', '2024-01-20 10:45:00');
    
    -- Insert dummy authentications (refresh tokens)
    INSERT INTO authentications (token, user_id, created_at)
    VALUES ('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huX2RvZSIsImlhdCI6MTcwNTM4MDYwMCwiZXhwIjoxNzA1NDY3MDAwfQ.refresh_token_1',
            1, '2024-01-20 10:30:00'),
           ('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lX3NtaXRoIiwiaWF0IjoxNzA1MzgwNjAwLCJleHAiOjE3MDU0NjcwMDB9.refresh_token_2',
            2, '2024-01-20 14:20:00'),
           ('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhaG1hZF9idWRpIiwiaWF0IjoxNzA1MzgwNjAwLCJleHAiOjE3MDU0NjcwMDB9.refresh_token_3',
            3, '2024-01-20 09:15:00');
    
    -- Insert dummy accounts
    INSERT INTO accounts (id, user_id, balance, currency, account_status, created_at, updated_at)
    VALUES ('2112443327', 1, 250000000.00, 'IDR', 'ACTIVE', '2024-01-15 10:30:00',
            '2024-01-20 15:45:00'),
           ('1211332156', 2, 180000000.00, 'IDR', 'ACTIVE', '2024-01-16 14:20:00',
            '2024-01-20 16:30:00'),
           ('1718211129', 3, 750000000.00, 'IDR', 'ACTIVE', '2024-01-17 09:15:00',
            '2024-01-20 12:20:00'),
           ('7667819120', 4, 0.00, 'IDR', 'SUSPENDED', '2024-01-18 16:45:00',
            '2024-01-19 10:00:00'),
           ('5665811721', 5, 500000000.00, 'IDR', 'ACTIVE', '2024-01-19 11:30:00',
            '2024-01-20 17:15:00');
    
    INSERT INTO external_services (id, company, service_type, contact_email, description, is_active, created_at,
                                   updated_at)
    VALUES ('8f7e6d5c-4b3a-4829-9876-5432109876ab', 'Bank Indonesia', 'TRANSACTION_API', 'api@bi.go.id',
            'Bank Indonesia Transaction Monitoring', true, now(), now()),
           ('2e8f6c4a-9b7d-4531-8642-97531086420f', 'Otoritas Jasa Keuangan (OJK)', 'TRANSACTION_API', 'api@ojk.go.id',
            'OJK Financial Services Monitoring', true, now(), now());
    
    INSERT INTO api_keys (id, external_service_id, key_name, permissions, rate_limit_count,
                          rate_limit_unit, expires_at, is_active, created_at, updated_at)
    VALUES ('a1b2c3d4-e5f6-4789-abcd-ef0123456789', '8f7e6d5c-4b3a-4829-9876-5432109876ab', 'Bank Indonesia Key',
            'READ_TRANSACTIONS', 1000, 'minute', '2025-01-20 10:30:00', true, now(), now()),
           ('f9e8d7c6-b5a4-4321-9876-543210987654', '2e8f6c4a-9b7d-4531-8642-97531086420f', 'OJK Key',
            'READ_TRANSACTIONS,READ_REPORTS', 500, 'minute', '2025-01-20 14:20:00', true, now(), now());
    
    INSERT INTO api_access_logs (id, external_service_id, api_key_id, endpoint, http_method, ip_address, user_agent,
                                 response_status, created_at)
    VALUES ('950e8400-e29b-41d4-a716-44665544000v', '8f7e6d5c-4b3a-4829-9876-5432109876ab',
            'a1b2c3d4-e5f6-4789-abcd-ef0123456789', '/api/transactions', 'GET',
            '203.34.118.1', 'BankIndonesia-Client/1.0', 200, '2024-01-20 10:15:00'),
           ('950e8400-e29b-41d4-a716-44665544000g', '2e8f6c4a-9b7d-4531-8642-97531086420f',
            'f9e8d7c6-b5a4-4321-9876-543210987654', '/api/transactions', 'GET',
            '45.112.89.234', 'OJK-DataMiner/2.1', 200, '2024-01-20 11:30:00'),
           ('950e8400-e29b-41d4-a716-446655440j9k', '8f7e6d5c-4b3a-4829-9876-5432109876ab',
            'a1b2c3d4-e5f6-4789-abcd-ef0123456789',
            '/api/transactions/TXN-20240115-001', 'GET', '203.34.118.1', 'BankIndonesia-Client/1.0', 200,
            '2024-01-20 12:45:00');