apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
  namespace: one-gate-payment
spec:
  serviceName: postgresql-service
  replicas: 1
  selector:
    matchLabels:
      app: one-gate-payment-db
  template:
    metadata:
      labels:
        app: one-gate-payment-db
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: postgresql
          image: quay.io/sclorg/postgresql-16-c9s:latest
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_DB
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "500"
            - name: POSTGRESQL_SHARED_BUFFERS
              value: "256MB"
            - name: POSTGRESQL_EFFECTIVE_CACHE_SIZE
              value: "1GB"

          ports:
            - containerPort: 5432
              name: postgresql

          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/pgsql/data

          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "2Gi"

          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - --live
            initialDelaySeconds: 120
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            periodSeconds: 5

  volumeClaimTemplates:
    - metadata:
        name: postgresql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi

---
# Service for one gate payment database
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: one-gate-payment
  labels:
    app: one-gate-payment-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: one-gate-payment-db