apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: one-gate-payment
  labels:
    app: one-gate-payment-db
type: Opaque
data:
  POSTGRES_USER: ZGV2ZWxvcGVy
  POSTGRES_PASSWORD: ZGV2ZWxvcGVyMTIz
  POSTGRES_DB: b25lX2dhdGVfcGF5bWVudA==