apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: one-gate-payment
  labels:
    app: one-gate-payment-db
data:
  postgresql.conf: |
    # PostgreSQL configuration for payment system
    max_connections = 500
    shared_buffers = 256MB
    effective_cache_size = 1GB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    
    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'pg_log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'all'
    log_min_duration_statement = 1000
    
    # Security
    ssl = off
    password_encryption = 'md5'
    
    # Performance for financial transactions
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    
    # Connection settings
    listen_addresses = '*'
    port = 5432