apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: one-gate-payment
data:
  kong.yaml: |
    _format_version: "3.0"
    _transform: true

    # Global plugins (like your script)
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          headers: ["Accept", "Accept-Version", "Content-Length", "Content-MD5", "Content-Type", "Date", "X-Auth-Token", "Authorization", "X-API-Key"]
          exposed_headers: ["X-Auth-Token"]
          credentials: true
          max_age: 3600
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
          policy: local

    # JWT Consumer (exactly like your script)
    consumers:
      - username: payment-app
        jwt_secrets:
          - algorithm: HS512
            key: "https://bni.co.id"
            secret: "e2926909a5c43ecea3ffa3b65fc747089755d687f401cd01e1a9372ab2d39e0700f108b7a6e739170e0cd25ef4f7bc9fdcc9b71de8d1be7e6e4490aa35d191a2"

    # Services and Routes (matching your script exactly)
    services:
      - name: authentication-service
        url: http://authentication-service:8080
        routes:
          - name: auth-register
            paths: ["/api/auth/register"]
            methods: ["POST"]
            strip_path: false
          - name: auth-login
            paths: ["/api/auth/login"]
            methods: ["POST"]
            strip_path: false
          - name: auth-refresh
            paths: ["/api/auth/refresh"]
            methods: ["PUT"]
            strip_path: false
          - name: auth-logout
            paths: ["/api/auth/logout"]
            methods: ["DELETE"]
            strip_path: false
      
      - name: payment-service
        url: http://payment-service:8080
        # JWT plugin applied to the entire service (like your script)
        plugins:
          - name: jwt
            config:
              secret_is_base64: false
              run_on_preflight: true
              claims_to_verify: ["exp"]
        routes:
          - name: payment-account
            paths: ["/api/payment/account"]
            methods: ["GET"]
            strip_path: false
          - name: payment-balance
            paths: ["/api/payment/balance"]
            methods: ["GET"]
            strip_path: false
          - name: payment-wallet
            paths: ["/api/payment/wallet"]
            methods: ["GET"]
            strip_path: false
          - name: payment-wallet-topup
            paths: ["/api/payment/wallet/topup"]
            methods: ["POST"]
            strip_path: false