apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-proxy
  namespace: one-gate-payment
  labels:
    app: kong-gateway
spec:
  to:
    kind: Service
    name: kong-proxy
  port:
    targetPort: proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-admin
  namespace: one-gate-payment
  labels:
    app: kong-gateway
spec:
  to:
    kind: Service
    name: kong-admin
  port:
    targetPort: admin
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-manager
  namespace: one-gate-payment
  labels:
    app: one-gate-payment
    component: gateway
spec:
  to:
    kind: Service
    name: kong-manager
  port:
    targetPort: admin-gui
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect