apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3200
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo
    compactor:
      compaction:
        block_retention: 24h
