- hosts: gcp-sonarqube
  become: yes
  vars:
    sonarqube_version: 9.9.1.69595
    sonarqube_dir: /opt/sonarqube-{{ sonarqube_version }}
    sonarqube_user: sonar

  tasks:
    - name: Install Java, unzip, wget
      apt:
        name:
          - openjdk-17-jdk
          - unzip
          - wget
        update_cache: yes

    - name: Download SonarQube
      get_url:
        url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
        dest: /tmp/sonarqube.zip

    - name: Unzip SonarQube
      unarchive:
        src: /tmp/sonarqube.zip
        dest: /opt/
        remote_src: yes
      notify: Restart SonarQube

    - name: Buat user sonar
      user:
        name: "{{ sonarqube_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Ubah hak akses SonarQube folder
      file:
        path: "{{ sonarqube_dir }}"
        owner: "{{ sonarqube_user }}"
        group: "{{ sonarqube_user }}"
        recurse: yes

    - name: Deploy systemd service file SonarQube
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=syslog.target network.target

          [Service]
          Type=forking
          ExecStart={{ sonarqube_dir }}/bin/linux-x86-64/sonar.sh start
          ExecStop={{ sonarqube_dir }}/bin/linux-x86-64/sonar.sh stop
          User={{ sonarqube_user }}
          Group={{ sonarqube_user }}
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Restart SonarQube

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Start & enable SonarQube
      systemd:
        name: sonarqube
        enabled: yes
        state: started

  handlers:
    - name: Restart SonarQube
      systemd:
        name: sonarqube
        state: restarted
