apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: one-gate-payment-kafka-nodes
  namespace: one-gate-payment
  labels:
    strimzi.io/cluster: one-gate-payment-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 20Gi
    class: ssd-csi
  resources:
    requests:
      memory: 4Gi
      cpu: 1000m
    limits:
      memory: 6Gi
      cpu: 2000m
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: one-gate-payment-kafka
  namespace: one-gate-payment
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      auto.create.topics.enable: "true"
      num.partitions: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}